services:
    app:
        container_name: python
        build:
            context: .
            dockerfile: .docker/python/DockerFile
        volumes:
        - ./:/app
        ports:
          - "8000:8000"
        command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 "

    pgsql:
        container_name: pgsql
        image: 'postgres'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - ./.docker/postgresql/data:/var/lib/postgresql/data
networks:
    app:
        driver: bridge