services:
  python:
    build:
      dockerfile: .docker/python/DockerFile
    command: uvicorn app.test:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      app-network:
        ipv4_address: 172.20.0.5 # Ваш статический IP
  webhook:
    image: localtonet/localtonet
    restart: unless-stopped
    command: localtonet/localtonet authtoken ${WEBHOOK_KEY}
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    volumes:
      - .docker/pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"

volumes:
  postgres_data:
