services:
    app:
        container_name: python
        build:
            context: .
            dockerfile: .docker/python/DockerFile
        volumes:
        - ./:/app
        ports:
          - "8000:8000"
        command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 "
        environment:
            DB_USER: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_HOST: ${DB_HOST}
            DB_DATABASE: ${DB_DATABASE}
    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
        - .docker/mysql/data:/var/lib/mysql  # Использует существующий том или создаёт новый
        - ./sql:/docker-entrypoint-initdb.d
        ports:
        - "${DB_PORT}:3306"
networks:
    app:
        driver: bridge