CREATE USER '{$MYSQL_USER}'@'{$DB_DATABASE}' IDENTIFIED BY '{$MYSQL_PASSWORD}';
GRANT CREATE, SELECT, INSERT, UPDATE, DELETE ON *.* TO '{$MYSQL_USER}'@'{$DB_DATABASE}';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS `python`.`bot_users` (
    `id` int unsigned NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(50) DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET=cp1251;