# Указываем базовый образ
FROM python:3.10

# Создаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем только requirements.txt
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Копируем остальные файлы проекта
COPY . .
