# Указываем базовый образ
FROM python:3.10

# Создаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем только requirements.txt
COPY requirements.txt .

# Создаем виртуальное окружение
RUN python3 -m venv /app/venv

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Копируем остальные файлы проекта
COPY . .
